# Generated by Django 4.2.6 on 2023-10-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='dept_id',
            new_name='dept_name',
        ),
    ]
